/**
 * MCP Swarm v1.0.0 - Smart Tools Index
 * Modular re-export of all 54 Smart Tools
 */

import { swarmAgentTool, swarmControlTool, swarmPulseTool, swarmCompanionTool } from "./core.js";
import { swarmTaskTool, swarmPlanTool, swarmBriefingTool, swarmSpecTool } from "./tasks.js";
import { swarmFileTool, swarmSnapshotTool, swarmWorktreeTool, swarmHooksTool } from "./files.js";
import { swarmGitTool, swarmDependencyTool } from "./git.js";
import { swarmChatTool, swarmReviewTool, swarmVotingTool, swarmAuctionTool, swarmMcpTool, swarmOrchestratorTool, swarmMessageTool } from "./collaboration.js";
import { swarmDefenceTool, swarmImmuneTool, swarmConsensusTool } from "./security.js";
import { swarmCostTool, swarmMoETool, swarmSONATool, swarmBudgetTool, swarmQualityTool, swarmRegressionTool } from "./analytics.js";
import { swarmVectorTool, swarmBoosterTool, swarmBatchTool, swarmBrainstormTool, swarmDebugTool, swarmContextTool, swarmContextPoolTool } from "./intelligence.js";
import { swarmExternalTool, swarmPlatformTool, swarmPreemptionTool, swarmExpertiseTool, swarmRoutingTool, swarmKnowledgeTool, swarmScreenshotTool, swarmSessionTool, swarmTimelineTool, swarmClustersTool, swarmDocsTool, swarmConflictTool, swarmHealthTool, swarmQaTool, swarmAdviceTool, swarmAutoReviewTool, swarmTelegramTool } from "./infra.js";

export {
  swarmAgentTool,
  swarmControlTool,
  swarmPulseTool,
  swarmCompanionTool,
  swarmTaskTool,
  swarmPlanTool,
  swarmBriefingTool,
  swarmSpecTool,
  swarmFileTool,
  swarmSnapshotTool,
  swarmWorktreeTool,
  swarmHooksTool,
  swarmGitTool,
  swarmDependencyTool,
  swarmChatTool,
  swarmReviewTool,
  swarmVotingTool,
  swarmAuctionTool,
  swarmMcpTool,
  swarmOrchestratorTool,
  swarmMessageTool,
  swarmDefenceTool,
  swarmImmuneTool,
  swarmConsensusTool,
  swarmCostTool,
  swarmMoETool,
  swarmSONATool,
  swarmBudgetTool,
  swarmQualityTool,
  swarmRegressionTool,
  swarmVectorTool,
  swarmBoosterTool,
  swarmBatchTool,
  swarmBrainstormTool,
  swarmDebugTool,
  swarmContextTool,
  swarmContextPoolTool,
  swarmExternalTool,
  swarmPlatformTool,
  swarmPreemptionTool,
  swarmExpertiseTool,
  swarmRoutingTool,
  swarmKnowledgeTool,
  swarmScreenshotTool,
  swarmSessionTool,
  swarmTimelineTool,
  swarmClustersTool,
  swarmDocsTool,
  swarmConflictTool,
  swarmHealthTool,
  swarmQaTool,
  swarmAdviceTool,
  swarmAutoReviewTool,
  swarmTelegramTool
};

export const allSmartTools = [
  swarmAgentTool,
  swarmControlTool,
  swarmPulseTool,
  swarmCompanionTool,
  swarmTaskTool,
  swarmPlanTool,
  swarmBriefingTool,
  swarmSpecTool,
  swarmFileTool,
  swarmSnapshotTool,
  swarmWorktreeTool,
  swarmHooksTool,
  swarmGitTool,
  swarmDependencyTool,
  swarmChatTool,
  swarmReviewTool,
  swarmVotingTool,
  swarmAuctionTool,
  swarmMcpTool,
  swarmOrchestratorTool,
  swarmMessageTool,
  swarmDefenceTool,
  swarmImmuneTool,
  swarmConsensusTool,
  swarmCostTool,
  swarmMoETool,
  swarmSONATool,
  swarmBudgetTool,
  swarmQualityTool,
  swarmRegressionTool,
  swarmVectorTool,
  swarmBoosterTool,
  swarmBatchTool,
  swarmBrainstormTool,
  swarmDebugTool,
  swarmContextTool,
  swarmContextPoolTool,
  swarmExternalTool,
  swarmPlatformTool,
  swarmPreemptionTool,
  swarmExpertiseTool,
  swarmRoutingTool,
  swarmKnowledgeTool,
  swarmScreenshotTool,
  swarmSessionTool,
  swarmTimelineTool,
  swarmClustersTool,
  swarmDocsTool,
  swarmConflictTool,
  swarmHealthTool,
  swarmQaTool,
  swarmAdviceTool,
  swarmAutoReviewTool,
  swarmTelegramTool
];
